name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: last stage
        run: echo "thank you all - bye!"
      - name: testing push
        run: echo "check the job again and again"
